In [518]:
import numpy as np
import pandas as pd

In [519]:
df = pd.read_csv("001_Farzad (2).csv", low_memory=False)
df

,Row,Timestamp,EventSource,SlideEvent,StimType,Duration,CollectionPhase,SourceStimuliName,EventSource.1,InputEventSource,...,Saccade Index,Saccade Index by Stimulus,Saccade Start,Saccade End,Saccade Duration,Saccade Amplitude,Saccade Peak Velocity,Saccade Peak Acceleration,Saccade Peak Deceleration,Saccade Direction
0,1,3.650740e+01,1.0,StartSlide,TestImage,3000000.0,StimuliDisplay,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,4.693490e+01,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,6.359570e+01,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,8.026610e+01,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,9.698610e+01,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236416,236417,3.000456e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236417,236418,3.000460e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,1.0,Mouse,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236418,236419,3.000473e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236419,236420,3.000475e+06,1.0,EndMedia,TestImage,3000000.0,StimuliDisplay,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236420,236421,3.000476e+06,1.0,EndSlide,TestImage,3000000.0,StimuliDisplay,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [520]:
df['Event Label'].unique()

array([nan, 'Onset of warning sound', 'Risk response',
       'Not responded sound '], dtype=object)

In [521]:
df['Event Label'] = df['Event Label'].astype(str)

In [522]:


# Create a group number based on the 'onset of warning sound' to 'risk response' sequence
df['group'] = None  # Initialize group column

# Assign group numbers to the rows where the event label is 'onset of warning sound'
group_num = 0
group_in = True
for idx, row in df.iterrows():
    if row['Event Label'] == 'Onset of warning sound':
        group_num += 1  # New group for a new sequence
        group_in = True
    if row['Event Label'] in ['Risk response']:
        df.at[idx, 'group'] = group_num  # Assign group number to these rows
        group_in = False
    elif pd.isna(df.at[idx, 'group']) and group_in:
        df.at[idx, 'group'] = group_num  # For rows in between, assign the same group number
    else:
        df.at[idx, 'group'] = 0

df

,Row,Timestamp,EventSource,SlideEvent,StimType,Duration,CollectionPhase,SourceStimuliName,EventSource.1,InputEventSource,...,Saccade Index by Stimulus,Saccade Start,Saccade End,Saccade Duration,Saccade Amplitude,Saccade Peak Velocity,Saccade Peak Acceleration,Saccade Peak Deceleration,Saccade Direction,group
0,1,3.650740e+01,1.0,StartSlide,TestImage,3000000.0,StimuliDisplay,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2,4.693490e+01,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,3,6.359570e+01,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,4,8.026610e+01,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,5,9.698610e+01,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236416,236417,3.000456e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
236417,236418,3.000460e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,1.0,Mouse,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
236418,236419,3.000473e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
236419,236420,3.000475e+06,1.0,EndMedia,TestImage,3000000.0,StimuliDisplay,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
236420,236421,3.000476e+06,1.0,EndSlide,TestImage,3000000.0,StimuliDisplay,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

# windows_size

In [523]:
# WINDOW_SIZE = 5000 #ms
# df['Start_Time'] = df.groupby('group')['Timestamp'].transform('first')
#
# # Filter the DataFrame to include only rows within the window size
# df = df[
#     (df['Timestamp'] >= df['Start_Time']) &
#     (df['Timestamp'] <= df['Start_Time'] + WINDOW_SIZE)
#     ]
# df[df['group'] != 0]

In [524]:
df = df[df['group'] != 0]

In [525]:
df

,Row,Timestamp,EventSource,SlideEvent,StimType,Duration,CollectionPhase,SourceStimuliName,EventSource.1,InputEventSource,...,Saccade Index by Stimulus,Saccade Start,Saccade End,Saccade Duration,Saccade Amplitude,Saccade Peak Velocity,Saccade Peak Acceleration,Saccade Peak Deceleration,Saccade Direction,group
9573,9574,1.239520e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
9574,9575,1.239554e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
9575,9576,1.239721e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
9576,9577,1.239836e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,1.0,Mouse,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
9577,9578,1.239866e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,1.0,Keyboard,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235915,235916,2.994939e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78
235916,235917,2.994956e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78
235917,235918,2.994973e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78
235918,235919,2.994989e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,8636.0,2994981.024,2995031.029,50.0056,6.586753,197.278958,6189.753569,-4799.746386,200.919175,78
235919,235920,2.994998e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78

In [526]:
# Method 2: More robust approach using first() and last() (handles single-row groups better)
response_times_robust = df.groupby('group')['Timestamp'].agg(first='first', last='last').assign(ResponseTime=lambda x: x['last'] - x['first']).reset_index()

df = pd.merge(df, response_times_robust[['group', 'ResponseTime']], on='group', how='left')

df

,Row,Timestamp,EventSource,SlideEvent,StimType,Duration,CollectionPhase,SourceStimuliName,EventSource.1,InputEventSource,...,Saccade Start,Saccade End,Saccade Duration,Saccade Amplitude,Saccade Peak Velocity,Saccade Peak Acceleration,Saccade Peak Deceleration,Saccade Direction,group,ResponseTime
0,9574,1.239520e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1153.003
1,9575,1.239554e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1153.003
2,9576,1.239721e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1153.003
3,9577,1.239836e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,1.0,Mouse,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1153.003
4,9578,1.239866e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,1.0,Keyboard,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1153.003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62038,235916,2.994939e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78,450.330
62039,235917,2.994956e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78,450.330
62040,235918,2.994973e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78,450.330
62041,235919,2.994989e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,2994981.024,2995031.029,50.0056,6.586753,197.278958,6189.753569,-4799.746386,200.919175,78,450.330
62042,235920,2.994998e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78,450.330

In [527]:
response_times_robust

    group        first          last  ResponseTime
0       1   123952.045  1.251050e+05     1153.0030
1       2   147746.240  1.486930e+05      946.7260
2       3   287340.050  2.879477e+05      607.6449
3       4   287950.231  2.883488e+05      398.6010
4       5   291967.918  2.962645e+05     4296.5769
..    ...          ...           ...           ...
73     74  2857701.022  2.863787e+06     6085.7910
74     75  2864203.797  2.957336e+06    93131.9720
75     76  2957336.936  2.957357e+06       19.7830
76     77  2969217.171  2.971355e+06     2137.5290
77     78  2994547.216  2.994998e+06      450.3300

[78 rows x 4 columns]

# windows_size

In [528]:
# windows_size
WINDOW_SIZE = 5000  #ms
df['Start_Time'] = df.groupby('group')['Timestamp'].transform('first')

# Filter the DataFrame to include only rows within the window size
df = df[
    (df['Timestamp'] >= df['Start_Time']) &
    (df['Timestamp'] <= df['Start_Time'] + WINDOW_SIZE)
    ]
df[df['group'] != 0]

,Row,Timestamp,EventSource,SlideEvent,StimType,Duration,CollectionPhase,SourceStimuliName,EventSource.1,InputEventSource,...,Saccade End,Saccade Duration,Saccade Amplitude,Saccade Peak Velocity,Saccade Peak Acceleration,Saccade Peak Deceleration,Saccade Direction,group,ResponseTime,Start_Time
0,9574,1.239520e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1153.003,123952.045
1,9575,1.239554e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1153.003,123952.045
2,9576,1.239721e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1153.003,123952.045
3,9577,1.239836e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,1.0,Mouse,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1153.003,123952.045
4,9578,1.239866e+05,NaN,NaN,NaN,NaN,NaN,Screen recording,1.0,Keyboard,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1153.003,123952.045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62038,235916,2.994939e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78,450.330,2994547.216
62039,235917,2.994956e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78,450.330,2994547.216
62040,235918,2.994973e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78,450.330,2994547.216
62041,235919,2.994989e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,2995031.029,50.0056,6.586753,197.278958,6189.753569,-4799.746386,200.919175,78,450.330,2994547.216
62042,235920,2.994998e+06,NaN,NaN,NaN,NaN,NaN,Screen recording,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78,450.330,2994547.216

# Remove NaN

In [529]:
final_data = df[["group","Timestamp","Fixation Duration","ET_PupilLeft","ET_PupilRight","Gaze Velocity","Gaze Acceleration","ResponseTime"]]

final_data = final_data.dropna()
final_data

,group,Timestamp,Fixation Duration,ET_PupilLeft,ET_PupilRight,Gaze Velocity,Gaze Acceleration,ResponseTime
1,1,1.239554e+05,200.1032,3.300476,3.571590,25.617793,1361.831291,1153.003
2,1,1.239721e+05,200.1032,3.302517,3.574849,13.936440,-700.791482,1153.003
5,1,1.239888e+05,200.1032,3.303718,3.575371,22.546497,514.758486,1153.003
6,1,1.240054e+05,200.1032,3.307630,3.577801,12.008560,-634.082068,1153.003
8,1,1.240221e+05,200.1032,3.308602,3.580798,21.559071,573.012361,1153.003
...,...,...,...,...,...,...,...,...
62036,78,2.994906e+06,483.3640,3.766273,4.083576,3.011417,-87.034320,450.330
62037,78,2.994923e+06,483.3640,3.768609,4.085508,7.888158,292.623197,450.330
62038,78,2.994939e+06,483.3640,3.782112,4.097337,8.044017,9.348572,450.330
62039,78,2.994956e+06,483.3640,3.785028,4.098883,7.074656,-58.126339,450.330
62040,78,2.994973e+06,483.3640,3.794598,4.106590,9.821020,164.539636,450.330

# Selection feature

In [530]:
# Define custom aggregation functions for CV and IQR
def cv(series):
    return series.std() / series.mean()

def iqr(series):
    return series.quantile(0.75) - series.quantile(0.25)

def calculate_response_time(group):
    first_timestamp = group['Timestamp'].min()
    last_timestamp = group['Timestamp'].max()
    return last_timestamp - first_timestamp

In [531]:
final_data

,group,Timestamp,Fixation Duration,ET_PupilLeft,ET_PupilRight,Gaze Velocity,Gaze Acceleration,ResponseTime
1,1,1.239554e+05,200.1032,3.300476,3.571590,25.617793,1361.831291,1153.003
2,1,1.239721e+05,200.1032,3.302517,3.574849,13.936440,-700.791482,1153.003
5,1,1.239888e+05,200.1032,3.303718,3.575371,22.546497,514.758486,1153.003
6,1,1.240054e+05,200.1032,3.307630,3.577801,12.008560,-634.082068,1153.003
8,1,1.240221e+05,200.1032,3.308602,3.580798,21.559071,573.012361,1153.003
...,...,...,...,...,...,...,...,...
62036,78,2.994906e+06,483.3640,3.766273,4.083576,3.011417,-87.034320,450.330
62037,78,2.994923e+06,483.3640,3.768609,4.085508,7.888158,292.623197,450.330
62038,78,2.994939e+06,483.3640,3.782112,4.097337,8.044017,9.348572,450.330
62039,78,2.994956e+06,483.3640,3.785028,4.098883,7.074656,-58.126339,450.330
62040,78,2.994973e+06,483.3640,3.794598,4.106590,9.821020,164.539636,450.330

In [532]:
grouped_df = final_data.groupby('group').agg({
    'Gaze Velocity': ['min', 'max', 'mean', 'std', 'median', 'skew', 'std', cv,iqr],  # CV and IQR for Gaze Velocity
    'Gaze Acceleration': ['min', 'max', 'mean', 'std', 'median', 'skew', 'std', cv,iqr],  # CV and IQR for Gaze Acceleration
    'Fixation Duration': ['min', 'max', 'mean', 'std', 'median', 'skew', 'std', cv,iqr],  # CV and IQR for Fixation Duration
    'ET_PupilLeft': ['min', 'max', 'mean', 'std', 'median', 'skew', 'std', cv,iqr],  # CV and IQR for ET_PupilLeft
    'ET_PupilRight': ['min', 'max', 'mean', 'std', 'median', 'skew', 'std', cv,iqr],  # CV and IQR for ET_PupilRight
    'ResponseTime' : 'first'
})

In [533]:
grouped_df.columns = [' '.join(col).strip() for col in grouped_df.columns.values]

In [534]:
grouped_df

,Gaze Velocity min,Gaze Velocity max,Gaze Velocity mean,Gaze Velocity std,Gaze Velocity median,Gaze Velocity skew,Gaze Velocity std,Gaze Velocity cv,Gaze Velocity iqr,Gaze Acceleration min,...,ET_PupilRight min,ET_PupilRight max,ET_PupilRight mean,ET_PupilRight std,ET_PupilRight median,ET_PupilRight skew,ET_PupilRight std,ET_PupilRight cv,ET_PupilRight iqr,ResponseTime first
group,,,,,,,,,,,,,,,,,,,,,
1,0.790732,26.052198,11.820760,6.712800,10.791945,0.482271,6.712800,0.567882,10.161744,-6237.668387,...,3.571590,3.921628,3.708192,0.104247,3.683909,0.462029,0.104247,0.028113,0.181350,1153.0030
2,0.782130,22.363844,8.587881,4.597695,8.058950,0.687287,4.597695,0.535370,5.606834,-3283.758851,...,3.154394,3.347843,3.277044,0.075368,3.322790,-0.621219,0.075368,0.022999,0.154710,946.7260
3,1.918318,21.526620,10.845496,5.375320,9.497377,0.275251,5.375320,0.495627,7.441104,-5614.493007,...,3.281332,3.372236,3.310183,0.028565,3.300432,0.984898,0.028565,0.008629,0.038221,607.6449
4,3.049681,25.550728,11.622733,5.773980,11.829389,0.534722,5.773980,0.496783,7.065351,-2968.318697,...,3.372555,3.506078,3.423633,0.044954,3.418630,0.385808,0.044954,0.013130,0.076834,398.6010
5,0.353328,29.934670,11.791817,7.060852,10.859913,0.516895,7.060852,0.598793,11.218430,-8378.911059,...,3.299398,3.450938,3.405349,0.029434,3.410101,-1.528084,0.029434,0.008644,0.035013,4296.5769
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,0.333804,28.745366,11.194743,6.861302,10.692716,0.489576,6.861302,0.612904,9.684659,-5202.456322,...,3.841551,3.997080,3.924968,0.044555,3.924273,-0.172343,0.044555,0.011352,0.058335,6085.7910
75,0.454524,41.673854,11.658238,7.436669,10.285116,0.996996,7.436669,0.637890,9.273365,-7937.522492,...,3.603414,4.611985,4.273507,0.290023,4.370123,-0.774877,0.290023,0.067865,0.439101,93131.9720
76,11.623068,11.623068,11.623068,NaN,11.623068,NaN,NaN,NaN,0.000000,578.853256,...,3.460114,3.460114,3.460114,NaN,3.460114,NaN,NaN,NaN,0.000000,19.7830
77,1.048388,37.516793,14.106313,7.865453,12.668789,0.702094,7.865453,0.557584,10.168124,-6716.837896,...,2.878174,3.831863,3.332024,0.171393,3.268683,0.548829,0.171393,0.051438,0.212741,2137.5290
78,1.670319,19.386915,7.952755,3.796969,7.706312,1.113235,3.796969,0.477441,4.299099,-964.583699,...,3.853290,4.106590,3.984940,0.084103,3.986878,-0.090997,0.084103,0.021105,0.145683,450.3300

In [535]:
grouped_df

,Gaze Velocity min,Gaze Velocity max,Gaze Velocity mean,Gaze Velocity std,Gaze Velocity median,Gaze Velocity skew,Gaze Velocity std,Gaze Velocity cv,Gaze Velocity iqr,Gaze Acceleration min,...,ET_PupilRight min,ET_PupilRight max,ET_PupilRight mean,ET_PupilRight std,ET_PupilRight median,ET_PupilRight skew,ET_PupilRight std,ET_PupilRight cv,ET_PupilRight iqr,ResponseTime first
group,,,,,,,,,,,,,,,,,,,,,
1,0.790732,26.052198,11.820760,6.712800,10.791945,0.482271,6.712800,0.567882,10.161744,-6237.668387,...,3.571590,3.921628,3.708192,0.104247,3.683909,0.462029,0.104247,0.028113,0.181350,1153.0030
2,0.782130,22.363844,8.587881,4.597695,8.058950,0.687287,4.597695,0.535370,5.606834,-3283.758851,...,3.154394,3.347843,3.277044,0.075368,3.322790,-0.621219,0.075368,0.022999,0.154710,946.7260
3,1.918318,21.526620,10.845496,5.375320,9.497377,0.275251,5.375320,0.495627,7.441104,-5614.493007,...,3.281332,3.372236,3.310183,0.028565,3.300432,0.984898,0.028565,0.008629,0.038221,607.6449
4,3.049681,25.550728,11.622733,5.773980,11.829389,0.534722,5.773980,0.496783,7.065351,-2968.318697,...,3.372555,3.506078,3.423633,0.044954,3.418630,0.385808,0.044954,0.013130,0.076834,398.6010
5,0.353328,29.934670,11.791817,7.060852,10.859913,0.516895,7.060852,0.598793,11.218430,-8378.911059,...,3.299398,3.450938,3.405349,0.029434,3.410101,-1.528084,0.029434,0.008644,0.035013,4296.5769
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,0.333804,28.745366,11.194743,6.861302,10.692716,0.489576,6.861302,0.612904,9.684659,-5202.456322,...,3.841551,3.997080,3.924968,0.044555,3.924273,-0.172343,0.044555,0.011352,0.058335,6085.7910
75,0.454524,41.673854,11.658238,7.436669,10.285116,0.996996,7.436669,0.637890,9.273365,-7937.522492,...,3.603414,4.611985,4.273507,0.290023,4.370123,-0.774877,0.290023,0.067865,0.439101,93131.9720
76,11.623068,11.623068,11.623068,NaN,11.623068,NaN,NaN,NaN,0.000000,578.853256,...,3.460114,3.460114,3.460114,NaN,3.460114,NaN,NaN,NaN,0.000000,19.7830
77,1.048388,37.516793,14.106313,7.865453,12.668789,0.702094,7.865453,0.557584,10.168124,-6716.837896,...,2.878174,3.831863,3.332024,0.171393,3.268683,0.548829,0.171393,0.051438,0.212741,2137.5290
78,1.670319,19.386915,7.952755,3.796969,7.706312,1.113235,3.796969,0.477441,4.299099,-964.583699,...,3.853290,4.106590,3.984940,0.084103,3.986878,-0.090997,0.084103,0.021105,0.145683,450.3300

In [536]:
grouped_df.isnull().sum()

Gaze Velocity min           0
Gaze Velocity max           0
Gaze Velocity mean          0
Gaze Velocity std           2
Gaze Velocity median        0
Gaze Velocity skew          2
Gaze Velocity std           2
Gaze Velocity cv            2
Gaze Velocity iqr           0
Gaze Acceleration min       0
Gaze Acceleration max       0
Gaze Acceleration mean      0
Gaze Acceleration std       2
Gaze Acceleration median    0
Gaze Acceleration skew      2
Gaze Acceleration std       2
Gaze Acceleration cv        2
Gaze Acceleration iqr       0
Fixation Duration min       0
Fixation Duration max       0
Fixation Duration mean      0
Fixation Duration std       2
Fixation Duration median    0
Fixation Duration skew      2
Fixation Duration std       2
Fixation Duration cv        2
Fixation Duration iqr       0
ET_PupilLeft min            0
ET_PupilLeft max            0
ET_PupilLeft mean           0
ET_PupilLeft std            2
ET_PupilLeft median         0
ET_PupilLeft skew           2
ET_PupilLeft std            2
ET_PupilLeft cv             2
ET_PupilLeft iqr            0
ET_PupilRight min           0
ET_PupilRight max           0
ET_PupilRight mean          0
ET_PupilRight std           2
ET_PupilRight median        0
ET_PupilRight skew          2
ET_PupilRight std           2
ET_PupilRight cv            2
ET_PupilRight iqr           0
ResponseTime first          0
dtype: int64

In [537]:
grouped_df =  grouped_df.dropna()
grouped_df.isnull().sum()

Gaze Velocity min           0
Gaze Velocity max           0
Gaze Velocity mean          0
Gaze Velocity std           0
Gaze Velocity median        0
Gaze Velocity skew          0
Gaze Velocity std           0
Gaze Velocity cv            0
Gaze Velocity iqr           0
Gaze Acceleration min       0
Gaze Acceleration max       0
Gaze Acceleration mean      0
Gaze Acceleration std       0
Gaze Acceleration median    0
Gaze Acceleration skew      0
Gaze Acceleration std       0
Gaze Acceleration cv        0
Gaze Acceleration iqr       0
Fixation Duration min       0
Fixation Duration max       0
Fixation Duration mean      0
Fixation Duration std       0
Fixation Duration median    0
Fixation Duration skew      0
Fixation Duration std       0
Fixation Duration cv        0
Fixation Duration iqr       0
ET_PupilLeft min            0
ET_PupilLeft max            0
ET_PupilLeft mean           0
ET_PupilLeft std            0
ET_PupilLeft median         0
ET_PupilLeft skew           0
ET_PupilLeft std            0
ET_PupilLeft cv             0
ET_PupilLeft iqr            0
ET_PupilRight min           0
ET_PupilRight max           0
ET_PupilRight mean          0
ET_PupilRight std           0
ET_PupilRight median        0
ET_PupilRight skew          0
ET_PupilRight std           0
ET_PupilRight cv            0
ET_PupilRight iqr           0
ResponseTime first          0
dtype: int64

In [538]:
grouped_df

,Gaze Velocity min,Gaze Velocity max,Gaze Velocity mean,Gaze Velocity std,Gaze Velocity median,Gaze Velocity skew,Gaze Velocity std,Gaze Velocity cv,Gaze Velocity iqr,Gaze Acceleration min,...,ET_PupilRight min,ET_PupilRight max,ET_PupilRight mean,ET_PupilRight std,ET_PupilRight median,ET_PupilRight skew,ET_PupilRight std,ET_PupilRight cv,ET_PupilRight iqr,ResponseTime first
group,,,,,,,,,,,,,,,,,,,,,
1,0.790732,26.052198,11.820760,6.712800,10.791945,0.482271,6.712800,0.567882,10.161744,-6237.668387,...,3.571590,3.921628,3.708192,0.104247,3.683909,0.462029,0.104247,0.028113,0.181350,1153.0030
2,0.782130,22.363844,8.587881,4.597695,8.058950,0.687287,4.597695,0.535370,5.606834,-3283.758851,...,3.154394,3.347843,3.277044,0.075368,3.322790,-0.621219,0.075368,0.022999,0.154710,946.7260
3,1.918318,21.526620,10.845496,5.375320,9.497377,0.275251,5.375320,0.495627,7.441104,-5614.493007,...,3.281332,3.372236,3.310183,0.028565,3.300432,0.984898,0.028565,0.008629,0.038221,607.6449
4,3.049681,25.550728,11.622733,5.773980,11.829389,0.534722,5.773980,0.496783,7.065351,-2968.318697,...,3.372555,3.506078,3.423633,0.044954,3.418630,0.385808,0.044954,0.013130,0.076834,398.6010
5,0.353328,29.934670,11.791817,7.060852,10.859913,0.516895,7.060852,0.598793,11.218430,-8378.911059,...,3.299398,3.450938,3.405349,0.029434,3.410101,-1.528084,0.029434,0.008644,0.035013,4296.5769
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,1.064127,16.910445,9.421829,4.691026,9.169273,-0.200063,4.691026,0.497889,3.586152,-950.748619,...,3.872995,3.885174,3.878296,0.004044,3.878319,0.283452,0.004044,0.001043,0.004149,125.4430
74,0.333804,28.745366,11.194743,6.861302,10.692716,0.489576,6.861302,0.612904,9.684659,-5202.456322,...,3.841551,3.997080,3.924968,0.044555,3.924273,-0.172343,0.044555,0.011352,0.058335,6085.7910
75,0.454524,41.673854,11.658238,7.436669,10.285116,0.996996,7.436669,0.637890,9.273365,-7937.522492,...,3.603414,4.611985,4.273507,0.290023,4.370123,-0.774877,0.290023,0.067865,0.439101,93131.9720
77,1.048388,37.516793,14.106313,7.865453,12.668789,0.702094,7.865453,0.557584,10.168124,-6716.837896,...,2.878174,3.831863,3.332024,0.171393,3.268683,0.548829,0.171393,0.051438,0.212741,2137.5290
78,1.670319,19.386915,7.952755,3.796969,7.706312,1.113235,3.796969,0.477441,4.299099,-964.583699,...,3.853290,4.106590,3.984940,0.084103,3.986878,-0.090997,0.084103,0.021105,0.145683,450.3300

In [539]:
grouped_df.columns

Index(['Gaze Velocity min', 'Gaze Velocity max', 'Gaze Velocity mean',
       'Gaze Velocity std', 'Gaze Velocity median', 'Gaze Velocity skew',
       'Gaze Velocity std', 'Gaze Velocity cv', 'Gaze Velocity iqr',
       'Gaze Acceleration min', 'Gaze Acceleration max',
       'Gaze Acceleration mean', 'Gaze Acceleration std',
       'Gaze Acceleration median', 'Gaze Acceleration skew',
       'Gaze Acceleration std', 'Gaze Acceleration cv',
       'Gaze Acceleration iqr', 'Fixation Duration min',
       'Fixation Duration max', 'Fixation Duration mean',
       'Fixation Duration std', 'Fixation Duration median',
       'Fixation Duration skew', 'Fixation Duration std',
       'Fixation Duration cv', 'Fixation Duration iqr', 'ET_PupilLeft min',
       'ET_PupilLeft max', 'ET_PupilLeft mean', 'ET_PupilLeft std',
       'ET_PupilLeft median', 'ET_PupilLeft skew', 'ET_PupilLeft std',
       'ET_PupilLeft cv', 'ET_PupilLeft iqr', 'ET_PupilRight min',
       'ET_PupilRight max', 'ET_PupilRight mean', 'ET_PupilRight std',
       'ET_PupilRight median', 'ET_PupilRight skew', 'ET_PupilRight std',
       'ET_PupilRight cv', 'ET_PupilRight iqr', 'ResponseTime first'],
      dtype='object')

In [540]:
grouped_df = grouped_df.rename(columns={'ResponseTime first': 'Response Time'})
grouped_df

,Gaze Velocity min,Gaze Velocity max,Gaze Velocity mean,Gaze Velocity std,Gaze Velocity median,Gaze Velocity skew,Gaze Velocity std,Gaze Velocity cv,Gaze Velocity iqr,Gaze Acceleration min,...,ET_PupilRight min,ET_PupilRight max,ET_PupilRight mean,ET_PupilRight std,ET_PupilRight median,ET_PupilRight skew,ET_PupilRight std,ET_PupilRight cv,ET_PupilRight iqr,Response Time
group,,,,,,,,,,,,,,,,,,,,,
1,0.790732,26.052198,11.820760,6.712800,10.791945,0.482271,6.712800,0.567882,10.161744,-6237.668387,...,3.571590,3.921628,3.708192,0.104247,3.683909,0.462029,0.104247,0.028113,0.181350,1153.0030
2,0.782130,22.363844,8.587881,4.597695,8.058950,0.687287,4.597695,0.535370,5.606834,-3283.758851,...,3.154394,3.347843,3.277044,0.075368,3.322790,-0.621219,0.075368,0.022999,0.154710,946.7260
3,1.918318,21.526620,10.845496,5.375320,9.497377,0.275251,5.375320,0.495627,7.441104,-5614.493007,...,3.281332,3.372236,3.310183,0.028565,3.300432,0.984898,0.028565,0.008629,0.038221,607.6449
4,3.049681,25.550728,11.622733,5.773980,11.829389,0.534722,5.773980,0.496783,7.065351,-2968.318697,...,3.372555,3.506078,3.423633,0.044954,3.418630,0.385808,0.044954,0.013130,0.076834,398.6010
5,0.353328,29.934670,11.791817,7.060852,10.859913,0.516895,7.060852,0.598793,11.218430,-8378.911059,...,3.299398,3.450938,3.405349,0.029434,3.410101,-1.528084,0.029434,0.008644,0.035013,4296.5769
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,1.064127,16.910445,9.421829,4.691026,9.169273,-0.200063,4.691026,0.497889,3.586152,-950.748619,...,3.872995,3.885174,3.878296,0.004044,3.878319,0.283452,0.004044,0.001043,0.004149,125.4430
74,0.333804,28.745366,11.194743,6.861302,10.692716,0.489576,6.861302,0.612904,9.684659,-5202.456322,...,3.841551,3.997080,3.924968,0.044555,3.924273,-0.172343,0.044555,0.011352,0.058335,6085.7910
75,0.454524,41.673854,11.658238,7.436669,10.285116,0.996996,7.436669,0.637890,9.273365,-7937.522492,...,3.603414,4.611985,4.273507,0.290023,4.370123,-0.774877,0.290023,0.067865,0.439101,93131.9720
77,1.048388,37.516793,14.106313,7.865453,12.668789,0.702094,7.865453,0.557584,10.168124,-6716.837896,...,2.878174,3.831863,3.332024,0.171393,3.268683,0.548829,0.171393,0.051438,0.212741,2137.5290
78,1.670319,19.386915,7.952755,3.796969,7.706312,1.113235,3.796969,0.477441,4.299099,-964.583699,...,3.853290,4.106590,3.984940,0.084103,3.986878,-0.090997,0.084103,0.021105,0.145683,450.3300

# Data is ready for train

In [541]:
grouped_df.columns

Index(['Gaze Velocity min', 'Gaze Velocity max', 'Gaze Velocity mean',
       'Gaze Velocity std', 'Gaze Velocity median', 'Gaze Velocity skew',
       'Gaze Velocity std', 'Gaze Velocity cv', 'Gaze Velocity iqr',
       'Gaze Acceleration min', 'Gaze Acceleration max',
       'Gaze Acceleration mean', 'Gaze Acceleration std',
       'Gaze Acceleration median', 'Gaze Acceleration skew',
       'Gaze Acceleration std', 'Gaze Acceleration cv',
       'Gaze Acceleration iqr', 'Fixation Duration min',
       'Fixation Duration max', 'Fixation Duration mean',
       'Fixation Duration std', 'Fixation Duration median',
       'Fixation Duration skew', 'Fixation Duration std',
       'Fixation Duration cv', 'Fixation Duration iqr', 'ET_PupilLeft min',
       'ET_PupilLeft max', 'ET_PupilLeft mean', 'ET_PupilLeft std',
       'ET_PupilLeft median', 'ET_PupilLeft skew', 'ET_PupilLeft std',
       'ET_PupilLeft cv', 'ET_PupilLeft iqr', 'ET_PupilRight min',
       'ET_PupilRight max', 'ET_PupilRight mean', 'ET_PupilRight std',
       'ET_PupilRight median', 'ET_PupilRight skew', 'ET_PupilRight std',
       'ET_PupilRight cv', 'ET_PupilRight iqr', 'Response Time'],
      dtype='object')

In [542]:

grouped_df.loc[:, 'Response Time'] = grouped_df['Response Time'] / 1000
# Remove rows where 'Response Time' is greater than 2000
grouped_df = grouped_df[grouped_df['Response Time'] <= 10]

In [543]:
X = grouped_df.drop(columns=['Response Time'])  # Exclude the columns you don't want to use
y = grouped_df['Response Time']  # Assuming 'response time' is the target variable

# Label statistics

In [545]:
# Descriptive statistics
stats = y.describe()

# Additional measures
mean = y.mean()
std_dev = y.std()
variance = y.var()
median = y.median()
skewness = y.skew()
kurtosis = y.kurtosis()

# Quantiles
q1 = np.percentile(y, 25)  # 25th percentile
q3 = np.percentile(y, 75)  # 75th percentile
iqr = q3 - q1  # Interquartile Range

# Outlier detection (using IQR method)
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr
# outliers = y[(y < lower_bound) | (y > upper_bound)]

# Print all the statistics
print("Descriptive Statistics:\n", stats)
print("\nAdditional Measures:")
print(f"Mean: {mean:.4f}")
print(f"Standard Deviation: {std_dev:.4f}")
print(f"Variance: {variance:.4f}")
print(f"Median: {median:.4f}")
print(f"Skewness: {skewness:.4f}")
print(f"Kurtosis: {kurtosis:.4f}")
print(f"Interquartile Range (IQR): {iqr:.4f}")
# print(f"Outliers (if any):\n{outliers}")

Descriptive Statistics:
 count    63.000000
mean      2.075469
std       2.205279
min       0.125443
25%       0.458867
50%       1.103953
75%       2.954731
max       9.371828
Name: Response Time, dtype: float64

Additional Measures:
Mean: 2.0755
Standard Deviation: 2.2053
Variance: 4.8633
Median: 1.1040
Skewness: 1.4369
Kurtosis: 1.2782
Interquartile Range (IQR): 2.4959
Outliers (if any):
group
14    6.970306
52    9.371828
68    7.320105
69    6.834085
Name: Response Time, dtype: float64

# Gussian SVM

In [546]:
from sklearn.model_selection import KFold, GridSearchCV
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Initialize KFold
kf = KFold(n_splits=5, shuffle=False)  # 5-fold cross-validation, change as needed

# Lists to store the performance metrics across folds
mse_scores = []
mae_scores = []
r2_scores = []

# Define the parameter grid for GridSearchCV
param_grid = {'C': [0.1, 1, 10], 'epsilon': [0.01, 0.1, 0.5], 'gamma': ['scale', 'auto']}

# K-fold cross-validation
for train_index, test_index in kf.split(X_scaled):
    # Split the data into training and test sets
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Initialize the GridSearchCV with SVR
    grid_search = GridSearchCV(SVR(kernel='rbf'), param_grid, cv=5, scoring='neg_mean_squared_error')

    # Fit the model on the training data
    grid_search.fit(X_train, y_train)

    # Get the best model from the grid search
    best_model = grid_search.best_estimator_

    # Make predictions using the best model
    y_pred = best_model.predict(X_test)

    # Calculate performance metrics
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    # Store the metrics for this fold
    mse_scores.append(mse)
    mae_scores.append(mae)
    r2_scores.append(r2)

# Calculate and print average scores
print(f'Average MSE: {np.mean(mse_scores):.4f}')
print(f'Average MAE: {np.mean(mae_scores):.4f}')
print(f'Average R-squared: {np.mean(r2_scores):.4f}')

Average MSE: 3.9584
Average MAE: 1.3168
Average R-squared: 0.1570

# Random Forest

In [547]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Split the data into training and test sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=20)

# Initialize the RandomForestRegressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42 , max_depth=1)

# Train the model
rf_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf_model.predict(X_test)

# Calculate and print performance metrics
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error (MSE): {mse:.4f}')
print(f'Mean Absolute Error (MAE): {mae:.4f}')
print(f'R-squared: {r2:.4f}')

Mean Squared Error (MSE): 6.9920
Mean Absolute Error (MAE): 1.9727
R-squared: 0.0043

# Gradient Boosting

In [548]:
from sklearn.ensemble import GradientBoostingRegressor

# K-fold cross-validation
kf = KFold(n_splits=5, shuffle=False)

# Lists to store the performance metrics
mse_scores = []
mae_scores = []
r2_scores = []

# Define the parameter grid for GradientBoostingRegressor
param_grid = {'n_estimators': [50, 100, 200], 'learning_rate': [0.01, 0.1, 0.2], 'max_depth': [3, 5, 7]}

# K-fold cross-validation
for train_index, test_index in kf.split(X_scaled):
    # Split the data into training and test sets
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Initialize GridSearchCV with GradientBoostingRegressor
    grid_search = GridSearchCV(GradientBoostingRegressor(), param_grid, cv=5, scoring='neg_mean_squared_error')

    # Fit the model
    grid_search.fit(X_train, y_train)

    # Get the best model from the grid search
    best_model = grid_search.best_estimator_

    # Make predictions and evaluate
    y_pred = best_model.predict(X_test)
    mse_scores.append(mean_squared_error(y_test, y_pred))
    mae_scores.append(mean_absolute_error(y_test, y_pred))
    r2_scores.append(r2_score(y_test, y_pred))

# Average performance metrics
print(f'Average MSE: {np.mean(mse_scores):.4f}')
print(f'Average MAE: {np.mean(mae_scores):.4f}')
print(f'Average R-squared: {np.mean(r2_scores):.4f}')

Average MSE: 5.1544
Average MAE: 1.7164
Average R-squared: -0.2304

#  K-Nearest Neighbors (KNN) Regressor

In [549]:
from sklearn.neighbors import KNeighborsRegressor

# K-fold cross-validation
kf = KFold(n_splits=5, shuffle=False)

# Lists to store the performance metrics
mse_scores = []
mae_scores = []
r2_scores = []

# Define the parameter grid for KNeighborsRegressor
param_grid = {'n_neighbors': [3, 5, 7, 10], 'weights': ['uniform', 'distance']}

# K-fold cross-validation
for train_index, test_index in kf.split(X_scaled):
    # Split the data into training and test sets
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Initialize GridSearchCV with KNeighborsRegressor
    grid_search = GridSearchCV(KNeighborsRegressor(), param_grid, cv=5, scoring='neg_mean_squared_error')

    # Fit the model
    grid_search.fit(X_train, y_train)

    # Get the best model from the grid search
    best_model = grid_search.best_estimator_

    # Make predictions and evaluate
    y_pred = best_model.predict(X_test)
    mse_scores.append(mean_squared_error(y_test, y_pred))
    mae_scores.append(mean_absolute_error(y_test, y_pred))
    r2_scores.append(r2_score(y_test, y_pred))

# Average performance metrics
print(f'Average MSE: {np.mean(mse_scores):.4f}')
print(f'Average MAE: {np.mean(mae_scores):.4f}')
print(f'Average R-squared: {np.mean(r2_scores):.4f}')

Average MSE: 4.3051
Average MAE: 1.5613
Average R-squared: -0.0552

# Linear Regression

In [550]:
from sklearn.linear_model import LinearRegression

# K-fold cross-validation
kf = KFold(n_splits=5, shuffle=False)

# Lists to store the performance metrics
mse_scores = []
mae_scores = []
r2_scores = []

# Initialize the Linear Regression model
lr_model = LinearRegression()

# K-fold cross-validation
for train_index, test_index in kf.split(X_scaled):
    # Split the data into training and test sets
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Fit the model
    lr_model.fit(X_train, y_train)

    # Make predictions and evaluate
    y_pred = lr_model.predict(X_test)
    mse_scores.append(mean_squared_error(y_test, y_pred))
    mae_scores.append(mean_absolute_error(y_test, y_pred))
    r2_scores.append(r2_score(y_test, y_pred))

# Average performance metrics
print(f'Average MSE: {np.mean(mse_scores):.4f}')
print(f'Average MAE: {np.mean(mae_scores):.4f}')
print(f'Average R-squared: {np.mean(r2_scores):.4f}')

Average MSE: 60.7692
Average MAE: 5.6696
Average R-squared: -19.0470

# 5. Neural Networks (MLPRegressor)

In [552]:
from sklearn.neural_network import MLPRegressor

# K-fold cross-validation
kf = KFold(n_splits=5, shuffle=False)

# Lists to store the performance metrics
mse_scores = []
mae_scores = []
r2_scores = []

# Define the parameter grid for MLPRegressor
param_grid = {'hidden_layer_sizes': [(50,), (100,)], 'activation': ['relu', 'tanh']}

# K-fold cross-validation
for train_index, test_index in kf.split(X_scaled):
    # Split the data into training and test sets
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Initialize GridSearchCV with MLPRegressor
    grid_search = GridSearchCV(MLPRegressor(max_iter=3000), param_grid, cv=5, scoring='neg_mean_squared_error')

    # Fit the model
    grid_search.fit(X_train, y_train)

    # Get the best model from the grid search
    best_model = grid_search.best_estimator_

    # Make predictions and evaluate
    y_pred = best_model.predict(X_test)
    mse_scores.append(mean_squared_error(y_test, y_pred))
    mae_scores.append(mean_absolute_error(y_test, y_pred))
    r2_scores.append(r2_score(y_test, y_pred))

# Average performance metrics
print(f'Average MSE: {np.mean(mse_scores):.4f}')
print(f'Average MAE: {np.mean(mae_scores):.4f}')
print(f'Average R-squared: {np.mean(r2_scores):.4f}')

Average MSE: 6.8468
Average MAE: 1.9928
Average R-squared: -0.6299